AWSTemplateFormatVersion: 2010-09-09
Description: Create Policies for GatsbyCloudPolicy_Cloudfront
Resources:
  MyCloudfrontPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: GatsbyBucketPolicy_Cloudfront
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Action:
          - cloudfront:CreateInvalidation
          Resource:
          - '*'