AWSTemplateFormatVersion: 2010-09-09
Description: Policies Template for GatsbyBucketPolicy_S3
Parameters:
  S3BucketName:
    Type: String
    Description: Name of the S3 Bucket

Resources:
      Policies:
      - PolicyName: GatsbyBucketPolicy_S3
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:GetBucketLocation
            Resource:
            - arn:aws:s3:::*
          - Effect: Allow
            Action:
            - s3:ListBucket
            Resource:
            - !Sub arn:aws:s3:::${S3BucketName}
          - Effect: Allow
            Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
            Resource:
            - !Sub arn:aws:s3:::${S3BucketName}/*

  