AWSTemplateFormatVersion: 2010-09-09
Description: Policies Template for GatsbyBucketPolicy_Cloudfront
  S3BucketName:
    Type: String
    Description: Name of the S3 Bucket

Resources:
          - Effect: Allow
            Action: 
            - cloudfront:CreateInvalidation
            Resource: "*"
  